### ISSUE TITLE
ExcludeCategory not working

### ISSUE THREAD

**Issue by arnonmoscona** [takari/takari-cpsuite#10]
I don't know whether ExcludeCategory is still supported, but the following compiles but does not exclude the integration tests:

``` java
@RunWith(Categories.class)
@Categories.ExcludeCategory(IntegrationTestCategory.class) // does not work
@Suite.SuiteClasses( { UnitTests.class })
public class UnitTestSuite {
}
```

The opposite direction _does_ work:

``` java
@RunWith(Categories.class)
@Categories.IncludeCategory(IntegrationTestCategory.class)
@Suite.SuiteClasses( { IntegrationTests.class })
public class IntegrationTestSuite {
}
```

I will try to also mark integration test _classes_ with a marker base class and exclude using `@ExcludeBaseTypeFilter` as a temporary work-around

**Comment by arnonmoscona** [comment]
Confirming that adding `@ClasspathSuite.ExcludeBaseTypeFilter(IntegrationTestClassMarker.class)` does work.

**Comment by arnonmoscona** [comment]
Oh, Forgot to mention, my maven dependency is:

``` xml
        <dependency>
            <groupId>io.takari.junit</groupId>
            <artifactId>takari-cpsuite</artifactId>
            <version>1.2.7</version>
            <scope>test</scope>
        </dependency>
```

**Comment by CarlJi** [comment]
Maybe i can provide the explanation for your issue.

ExcludeCategory is the feature of Junit4 runner Categories, which is not part of ClasspathSuite, it aims to exclude all the test cases which are marked with specific annotation, in this case, it was IntegrationTestCategory.class. 

So if your test cases in the suite generated by @Suite.SuiteClasses( { UnitTests.class }) do have the annotation IntegrationTestCategory.class marked, it should be excluded. It is the function of Junit4 categories runner.

**Comment by arnonmoscona** [comment]
I'll have to investigate more. It clearly does not work in my case. I believe you that there _should be_ no side effect between `ClassPathSuite` and this feature. Maybe it's because I only marken full test classes with the category and not individual tests... I'll check as soon as I can.

Closing the issue in the meanwhile.
