### ISSUE TITLE
Doesn't work with Java 6

### ISSUE THREAD

**Issue by cdman** [takari/takari-cpsuite#3]
Even though the release note says "compiled with Java 6" the actual bytecode in the JAR on Maven Central [1] is of version 51 which means Java 7 [2]. Could you please set source/target version to 1.6 on the maven-compiler-plugin and recompile / publish a new version compatible with Java 6? Ie. something like this:

```
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
```

Thank you

[1] http://search.maven.org/remotecontent?filepath=io/takari/junit/takari-cpsuite/1.2.7/takari-cpsuite-1.2.7.jar
[2] http://en.wikipedia.org/wiki/Java_class_file

**Comment by jvanzyl** [comment]
I will fix up the notes. Java 1.6 is not going to be supported. I took over the project and I have no interest in supporting 1.6.

**Comment by cdman** [comment]
Thank you for the clarification. I'm hoping to push the project as soon as possible to Java 8 :-)
